### ISSUE TITLE
Cannot access a disposed object after upgrading to Xamarin.Forms 2.3.1.114

### ISSUE THREAD

**Issue by MaskPZ** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#12]
Hi James, 

First of all thank you for your great work! I'm using this control since time and it always worked perfectly!

A few days ago, I've updated to Xamarin.Forms 2.3.1.114 and since then...when I open the page containing the control the first time everything is ok but if I try to re-open it I get this:

"Unhandled Exception:    System.ObjectDisposedException: Cannot access a disposed object.  
Object name: 'Refractored.XamForms.PullToRefresh.Droid.PullToRefreshLayoutRenderer'."

Same error also after app resume.

As you can see it's on Android, never tried on iOS.

Hope you will fix it.

Thank you

**Comment by allbdeveloper** [comment]
"Cannot access a disposed object.
Object name: 'Refractored.XamForms.PullToRefresh.Droid.PullToRefreshLayoutRenderer'."

When I use camera from Xam.Plugin.Media. 
I got same exception.

forms version is 2.3.1.114.

**Comment by DotControlNB** [comment]
I got the same problem on a specific page in my application. First time opening it is not problem, but the second time it crashes with the error. My Xamarin.Forms version is 2.3.0.107. I can also confirm it's Android only. If it helps, in my case it's a page that is added as a child of a tabbed page. But the weird thing is I don't use the pulltorefresh functionality on that page.

**Comment by DotControlNB** [comment]
I did some debugging today, it seems that it has to do with using the `PullToRefreshLayout` in a `ContentView`. It was not working very well from a user perspective anyway, so I just moved it to my parent (`ContentPage`) page where I already included this `ContentView`. I no longer get this crash now, so it seems to be resolved. I don't know if the others that posted here have or had the same situation?

**Comment by j-monteiro** [comment]
Hi!

Since I updated Xamarin Forms to v2.3.2.127 i'm getting this exception while using PullToRefreshlayout. 
I'm using the pull to refresh in a Content Page.
To reproduce the problem I have to open the View once, close the View, open the View again and rotate the device to landscape mode.
If i rotate the device in the first time I open the View, the app don´t crash.

**Comment by LeoJHarris** [comment]
@DotControlNB My PullToRefresh is nested in a ContentPage and still the app crashes..

**Comment by Tetius** [comment]
It seems to happen when navigating to a TabbedPage before navigating to a page containing PullToRefreshLayout.

1. Navigate to page with PullToRefreshLayout
2. Navigate to TabbedPage
3. Navigate to page with PullToRefreshLayout

**Comment by j-monteiro** [comment]
Still with this problem :s the component is so good but after uptading xamarin forms it started to have this problem. Since no one atached the exception here it is:

Fatal Exception: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
Caused by android.runtime.JavaProxyThrowable: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Refractored.XamForms.PullToRefresh.Droid.PullToRefreshLayoutRenderer'.
  at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00030] in <a043032cf94a485190047a14918b9f60>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualBooleanMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00001] in <a043032cf94a485190047a14918b9f60>:0 
  at Android.Views.View.get_IsInLayout () [0x0000a] in <148efd2f7a03496fb40611cf5f4f0bb1>:0 
  at Xamarin.Forms.Platform.Android.VisualElementTracker.MaybeRequestLayout () [0x00016] in <95895bcb439e42ebb8e7134a545f1acc>:0 
  at Xamarin.Forms.Platform.Android.VisualElementTracker.HandleRedrawNeeded (System.Object sender, Xamarin.Forms.EventArg`1[T] e) [0x00049] in <95895bcb439e42ebb8e7134a545f1acc>:0 
  at (wrapper delegate-invoke) System.EventHandler`1[Xamarin.Forms.EventArg`1[Xamarin.Forms.VisualElement]]:invoke_void_object_TEventArgs (object,Xamarin.Forms.EventArg`1<Xamarin.Forms.VisualElement>)
  at Xamarin.Forms.VisualElement.BatchCommit () [0x00031] in <b0fc14d4e5b04749b7241d1235a68329>:0 
  at Xamarin.Forms.VisualElement.set_Bounds (Xamarin.Forms.Rectangle value) [0x00071] in <b0fc14d4e5b04749b7241d1235a68329>:0 
  at Xamarin.Forms.VisualElement.Layout (Xamarin.Forms.Rectangle bounds) [0x00000] in <b0fc14d4e5b04749b7241d1235a68329>:0 
  at Xamarin.Forms.Layout.LayoutChildIntoBoundingRegion (Xamarin.Forms.VisualElement child, Xamarin.Forms.Rectangle region) [0x0016b] in <b0fc14d4e5b04749b7241d1235a68329>:0 
  at Xamarin.Forms.Page.LayoutChildren (System.Double x, System.Double y, System.Double width, System.Double height) [0x00111] in <b0fc14d4e5b04749b7241d1235a68329>:0 
  at Xamarin.Forms.Page.UpdateChildrenLayout () [0x000d0] in <b0fc14d4e5b04749b7241d1235a68329>:0 
  at Xamarin.Forms.Page.OnSizeAllocated (System.Double width, System.Double height) [0x0000f] in <b0fc14d4e5b04749b7241d1235a68329>:0 
  at Xamarin.Forms.VisualElement.SizeAllocated (System.Double width, System.Double height) [0x00000] in <b0fc14d4e5b04749b7241d1235a68329>:0 
  at Xamarin.Forms.VisualElement.SetSize (System.Double width, System.Double height) [0x00021] in <b0fc14d4e5b04749b7241d1235a68329>:0 
  at Xamarin.Forms.VisualElement.set_Bounds (Xamarin.Forms.Rectangle value) [0x0006c] in <b0fc14d4e5b04749b7241d1235a68329>:0 
  at Xamarin.Forms.VisualElement.Layout (Xamarin.Forms.Rectangle bounds) [0x00000] in <b0fc14d4e5b04749b7241d1235a68329>:0 
  at Xamarin.Forms.Layout.LayoutChildIntoBoundingRegion (Xamarin.Forms.VisualElement child, Xamarin.Forms.Rectangle region) [0x0000a] in <b0fc14d4e5b04749b7241d1235a68329>:0 
  at Xamarin.Forms.Page.LayoutChildren (System.Double x, System.Double y, System.Double width, System.Double height) [0x00111] in <b0fc14d4e5b04749b7241d1235a68329>:0 
  at Xamarin.Forms.Page.UpdateChildrenLayout () [0x000d0] in <b0fc14d4e5b04749b7241d1235a68329>:0 
  at Xamarin.Forms.Page.OnSizeAllocated (System.Double width, System.Double height) [0x0000f] in <b0fc14d4e5b04749b7241d1235a68329>:0 
  at Xamarin.Forms.VisualElement.SizeAllocated (System.Double width, System.Double height) [0x00000] in <b0fc14d4e5b04749b7241d1235a68329>:0 
  at Xamarin.Forms.Page.ForceLayout () [0x0000d] in <b0fc14d4e5b04749b7241d1235a68329>:0 
  at Xamarin.Forms.Page.Xamarin.Forms.IPageController.set_ContainerArea (Xamarin.Forms.Rectangle value) [0x0001d] in <b0fc14d4e5b04749b7241d1235a68329>:0 
  at Xamarin.Forms.Platform.Android.AppCompat.TabbedPageRenderer.OnLayout (System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x000d1] in <95895bcb439e42ebb8e7134a545f1acc>:0 
  at Xamarin.Forms.Platform.Android.FormsViewGroup.n_OnLayout_ZIIII (System.IntPtr jnienv, System.IntPtr native__this, System.Boolean p0, System.Int32 p1, System.Int32 p2, System.Int32 p3, System.Int32 p4) [0x00008] in <97e56f29d2644ef29e4434660941acc4>:0 
  at (wrapper dynamic-method) System.Object:69f842f3-b64c-435b-87ab-6aa9ab9a9097 (intptr,intptr,bool,int,int,int,int)
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <368820a9888f43ddb85d18e87189adbf>:0 
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x000a7] in <a043032cf94a485190047a14918b9f60>:0 
  at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (System.IntPtr jobject, System.IntPtr jclass, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x00015] in <148efd2f7a03496fb40611cf5f4f0bb1>:0 
  at Xamarin.Forms.Platform.Android.FormsViewGroup.MeasureAndLayout (System.Int32 p0, System.Int32 p1, System.Int32 p2, System.Int32 p3, System.Int32 p4, System.Int32 p5) [0x000f6] in <97e56f29d2644ef29e4434660941acc4>:0 
  at Xamarin.Forms.Platform.Android.VisualElementTracker.UpdateLayout () [0x000bc] in <95895bcb439e42ebb8e7134a545f1acc>:0 
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].UpdateLayout () [0x0000e] in <95895bcb439e42ebb8e7134a545f1acc>:0 
  at Xamarin.Forms.Platform.Android.PageContainer.OnLayout (System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x00006] in <95895bcb439e42ebb8e7134a545f1acc>:0 
  at Android.Views.ViewGroup.n_OnLayout_ZIIII (System.IntPtr jnienv, System.IntPtr native__this, System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x00009] in <148efd2f7a03496fb40611cf5f4f0bb1>:0 
  at (wrapper dynamic-method) System.Object:d4d27620-e0cf-4782-b6dd-c6b126a1c3c5 (intptr,intptr,bool,int,int,int,int)
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <368820a9888f43ddb85d18e87189adbf>:0 
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x000a7] in <a043032cf94a485190047a14918b9f60>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00020] in <a043032cf94a485190047a14918b9f60>:0 
  at Android.Views.ViewGroup.Layout (System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x0005f] in <148efd2f7a03496fb40611cf5f4f0bb1>:0 
  at Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.OnLayout (System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x0011b] in <95895bcb439e42ebb8e7134a545f1acc>:0 
  at Xamarin.Forms.Platform.Android.FormsViewGroup.n_OnLayout_ZIIII (System.IntPtr jnienv, System.IntPtr native__this, System.Boolean p0, System.Int32 p1, System.Int32 p2, System.Int32 p3, System.Int32 p4) [0x00008] in <97e56f29d2644ef29e4434660941acc4>:0 
  at (wrapper dynamic-method) System.Object:69f842f3-b64c-435b-87ab-6aa9ab9a9097 (intptr,intptr,bool,int,int,int,int)
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <368820a9888f43ddb85d18e87189adbf>:0 
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x000a7] in <a043032cf94a485190047a14918b9f60>:0 
  at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (System.IntPtr jobject, System.IntPtr jclass, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x00015] in <148efd2f7a03496fb40611cf5f4f0bb1>:0 
  at Xamarin.Forms.Platform.Android.FormsViewGroup.MeasureAndLayout (System.Int32 p0, System.Int32 p1, System.Int32 p2, System.Int32 p3, System.Int32 p4, System.Int32 p5) [0x000f6] in <97e56f29d2644ef29e4434660941acc4>:0 
  at Xamarin.Forms.Platform.Android.VisualElementTracker.UpdateLayout () [0x000bc] in <95895bcb439e42ebb8e7134a545f1acc>:0 
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].UpdateLayout () [0x0000e] in <95895bcb439e42ebb8e7134a545f1acc>:0 
  at Xamarin.Forms.Platform.Android.MasterDetailContainer.OnLayout (System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x0004d] in <95895bcb439e42ebb8e7134a545f1acc>:0 
  at Xamarin.Forms.Platform.Android.AppCompat.MasterDetailContainer.OnLayout (System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x00000] in <95895bcb439e42ebb8e7134a545f1acc>:0 
  at Android.Views.ViewGroup.n_OnLayout_ZIIII (System.IntPtr jnienv, System.IntPtr native__this, System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x00009] in <148efd2f7a03496fb40611cf5f4f0bb1>:0 
  at (wrapper dynamic-method) System.Object:d4d27620-e0cf-4782-b6dd-c6b126a1c3c5 (intptr,intptr,bool,int,int,int,int)
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <368820a9888f43ddb85d18e87189adbf>:0 
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x000a7] in <a043032cf94a485190047a14918b9f60>:0 
  at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (System.IntPtr jobject, System.IntPtr jclass, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x00015] in <148efd2f7a03496fb40611cf5f4f0bb1>:0 
  at Android.Support.V4.Widget.DrawerLayout.OnLayout (System.Boolean changed, System.Int32 lValue, System.Int32 tValue, System.Int32 rValue, System.Int32 bValue) [0x000e5] in <27c17fe440cf491ba8255bcefade6e02>:0 
  at Xamarin.Forms.Platform.Android.AppCompat.MasterDetailPageRenderer.OnLayout (System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x00000] in <95895bcb439e42ebb8e7134a545f1acc>:0 
  at Android.Support.V4.Widget.DrawerLayout.n_OnLayout_ZIIII (System.IntPtr jnienv, System.IntPtr native__this, System.Boolean changed, System.Int32 lValue, System.Int32 tValue, System.Int32 rValue, System.Int32 bValue) [0x00009] in <27c17fe440cf491ba8255bcefade6e02>:0 
  at (wrapper dynamic-method) System.Object:77d506cb-fb49-4567-a9ba-ad5e7ca80734 (intptr,intptr,bool,int,int,int,int)
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <368820a9888f43ddb85d18e87189adbf>:0 
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x000a7] in <a043032cf94a485190047a14918b9f60>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00020] in <a043032cf94a485190047a14918b9f60>:0 
  at Android.Views.ViewGroup.Layout (System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x0005f] in <148efd2f7a03496fb40611cf5f4f0bb1>:0 
  at Xamarin.Forms.Platform.Android.VisualElementTracker.UpdateLayout () [0x00090] in <95895bcb439e42ebb8e7134a545f1acc>:0 
  at Xamarin.Forms.Platform.Android.AppCompat.MasterDetailPageRenderer.Xamarin.Forms.Platform.Android.IVisualElementRenderer.UpdateLayout () [0x0000a] in <95895bcb439e42ebb8e7134a545f1acc>:0 
  at Xamarin.Forms.Platform.Android.AppCompat.Platform.Xamarin.Forms.Platform.Android.IPlatformLayout.OnLayout (System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x00022] in <95895bcb439e42ebb8e7134a545f1acc>:0 
  at Xamarin.Forms.Platform.Android.PlatformRenderer.OnLayout (System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x00018] in <95895bcb439e42ebb8e7134a545f1acc>:0 
  at Android.Views.ViewGroup.n_OnLayout_ZIIII (System.IntPtr jnienv, System.IntPtr native__this, System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x00009] in <148efd2f7a03496fb40611cf5f4f0bb1>:0 
  at (wrapper dynamic-method) System.Object:d4d27620-e0cf-4782-b6dd-c6b126a1c3c5 (intptr,intptr,bool,int,int,int,int)
       at md5b60ffeb829f638581ab2bb9b1a7f4f3f.PlatformRenderer.n_onLayout(PlatformRenderer.java)
       at md5b60ffeb829f638581ab2bb9b1a7f4f3f.PlatformRenderer.onLayout(PlatformRenderer.java:63)
       at android.view.View.layout(View.java:16075)
       at android.view.ViewGroup.layout(ViewGroup.java:5300)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
       at android.view.View.layout(View.java:16075)
       at android.view.ViewGroup.layout(ViewGroup.java:5300)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
       at android.view.View.layout(View.java:16075)
       at android.view.ViewGroup.layout(ViewGroup.java:5300)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
       at android.view.View.layout(View.java:16075)
       at android.view.ViewGroup.layout(ViewGroup.java:5300)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
       at android.view.View.layout(View.java:16075)
       at android.view.ViewGroup.layout(ViewGroup.java:5300)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
       at android.view.View.layout(View.java:16075)
       at android.view.ViewGroup.layout(ViewGroup.java:5300)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
       at android.view.View.layout(View.java:16075)
       at android.view.ViewGroup.layout(ViewGroup.java:5300)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2119)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1873)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1073)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5988)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
       at android.view.Choreographer.doCallbacks(Choreographer.java:580)
       at android.view.Choreographer.doFrame(Choreographer.java:550)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5910)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

**Comment by mperetz** [comment]
We are still getting this Cannot access a disposed object exception, the control is very good, but we can't find the solution to this bug... 

We tried to override the dispose method, move things around... but nothing helps. I don't know if this is an issue with the control or if it is a Xamarin bug.

**Comment by MaskPZ** [comment]
I don't know if it's only me, but with Android I still have the same issue. Xamarin version 2.3.2.127. In your fix I can see only some code about iOS (PullToRefresh/PullToRefresh.iOS/PullToRefreshLayoutRenderer.cs) but nothing about Android. So the issue is still there.

Thanks

**Comment by topsites** [comment]
confirming the same error under droid

**Comment by jamesmontemagno** [comment]
Does anyone have a small repo they can attach

**Comment by MaskPZ** [comment]
Hi James,

Attached.

Thanks.

[PullToRefreshLayout Android error.txt](https://github.com/jamesmontemagno/Xamarin.Forms-PullToRefreshLayout/files/626709/PullToRefreshLayout.Android.error.txt)

**Comment by jamesmontemagno** [comment]
I need sample code that I can run and reproduce please.

**Comment by mrtnld** [comment]
Hi James
I don't think you have anything to fix in this project.
It looks like the bug is in Xamarin Forms and not fixed yet.
https://bugzilla.xamarin.com/show_bug.cgi?id=42678
Regards :-)

**Comment by andrii-borysov-me** [comment]
Hi @jamesmontemagno,

You need to properly implement the `Dispose` method to fix this problem. Probably, it would be enough to do `Element.PropertyChanged -= HandlePropertyChanged`. But please check how other renderers in Xamarin.Android are implemented, and what they do in `Dispose`.

**Comment by jamesmontemagno** [comment]
pushing a new beta out to try out.

**Comment by 22222** [comment]
Here's a sample app that reproduces the issue for me: https://github.com/22222/XamarinFormsTestApp.  I still get the exception with those new changes to the renderer's `Dispose` method.

At least for the way I've run into the issue, the key steps seem to be:

1. Set the `PullToRefreshLayout` as the `Content` of a `ContentPage`
2. Replace the `PullToRefreshLayout` with some other view
3. Put that same `PullToRefreshLayout` back as the Content

When you remove the `PullToRefreshLayout` as the `Content` (step 2), the Android `PullToRefreshLayoutRenderer`'s `Dispose` method is called.  Then when you set it back as the content (step 3), you get that exception because the Android `SwipeRefreshLayout` is disposed.

If you use a `ScrollView` or `ListView` instead of a `PullToRefreshLayout`, then the above steps work fine and you don't get the `ObjectDisposedException`.  So there must be something that those renderers are doing differently?

**Comment by nazgul87** [comment]
Hi I'm using 1.2.0.4-beta version with Xamarin.Forms v2.3.3.180 and still gets the error. Which is the maximum version of Xamarin.Forms I have to use to avoid that issue?

**Comment by jamesmontemagno** [comment]
@22222 the issue here from your code is that when you replace the "Content" with the activity indicator then Xamarin.Forms disposes of your UI, but then you are setting it back so it is already disposed. Since I am disposing of everything properly that is why. This may be a change in how XF worked though.

It apparently only happens when not in a navigation page from my testing.

I have adjusted how it works with my dispose so the next beta shoudl work there.

I have now fixed this for Android. If there is still an issue with iOS please let me know and open a NEW issue with a proper sample repo that I can test.

**Comment by aherrick** [comment]
I've updated to the latest beta `1.2.0.5-beta` and am still seeing this crash. 

Occurs when the device is rotated after clicking through a few tabs. Droid only. Anyone figure out a work around here? 

Stack trace below:

[stack.txt](https://github.com/jamesmontemagno/Xamarin.Forms-PullToRefreshLayout/files/853295/stack.txt)

**Comment by keneniah** [comment]
Same here, don't have to rotate, just flip through a few pages. Then the app crashes with the above error message. Please reopen this thread again.

**Comment by jamesmontemagno** [comment]
If someone wants to put a use case in the sample app I can try to diagnose.

**Comment by Batman2k** [comment]
I get this error on tabbedpage everytime i'm trying to rotate with atleast 1 tab inbetween the page i'm rotating on and a page that contains PullToRefresh, i'm trying on android with forms 2.3.4.221-pre6 and PullToRefresh 1.2.0.5b.

To clarify, if i have a tabbedpage with 3 tabs and put PullToRefresh in tab 1 and rotate on tab3 it will crash(works on tab2), if i would instead put PullToRefresh in tab 2 then it will work fine to refresh on both tab1 and tab2.

It also crashes if i use TakePhotoAsync() with your plugin.media instead of rotating so i assume it's everytime the page have to refresh/rebuild the ui.

**Comment by SeeD-Seifer** [comment]
I have the same crash. Have no idea yet how to workaround it.

**Comment by LRPalacios** [comment]
Is this fixed?

**Comment by corentinaltepe** [comment]
Hi, is there a wordaround. I have the same issue. I can't reproduce it very clearly, and I can't trace back to the issue. Is there a way to avoid it?

**Comment by jamesmontemagno** [comment]
I have a new 2.0.0-beta that i just pushed, that may work better in some instances. It seems like a lot of issues are when you cache a page or view around for use later.

I am working with the forms team later this week to see if something weird is going on.

**Comment by hardcodet** [comment]
If helpful - shorter stack trace of the same issue. I'm seeing this occasionally but rarely happening with XF 2.3.4.247

```
Xamarin caused by: android.runtime.JavaProxyThrowable: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Refractored.XamForms.PullToRefresh.Droid.PullToRefreshLayoutRenderer'.
Java.Interop.JniPeerMembers.AssertSelf(IJavaPeerable self)<efcdcdca54d241a682e3c423f0aa3fc6>:0
Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualBooleanMethod(string encodedMember, IJavaPeerable self, JniArgumentValue* parameters)<efcdcdca54d241a682e3c423f0aa3fc6>:0
Android.Views.View.get_IsInLayout()<6d5b488990324d4ca6d28e34a1cffa58>:0
Xamarin.Forms.Platform.Android.VisualElementTracker.MaybeRequestLayout()<1481f85a917c4f2b882ea161e9bc082f>:0
Xamarin.Forms.Platform.Android.VisualElementTracker.HandleRedrawNeeded(object sender, EventArg<T> e)<1481f85a917c4f2b882ea161e9bc082f>:0
System.EventHandler<EventArg<VisualElement>>.invoke_void_object_TEventArgs(object, EventArg<VisualElement>)(wrapper delegate-invoke)
Xamarin.Forms.VisualElement.BatchCommit()<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.VisualElement.set_Bounds(Rectangle value)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.VisualElement.Layout(Rectangle bounds)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.Layout.LayoutChildIntoBoundingRegion(VisualElement child, Rectangle region)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.ContentPresenter.LayoutChildren(double x, double y, double width, double height)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.Layout.UpdateChildrenLayout()<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.Layout.OnSizeAllocated(double width, double height)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.VisualElement.SizeAllocated(double width, double height)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.VisualElement.SetSize(double width, double height)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.VisualElement.set_Bounds(Rectangle value)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.VisualElement.Layout(Rectangle bounds)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.Layout.LayoutChildIntoBoundingRegion(VisualElement child, Rectangle region)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.Grid.LayoutChildren(double x, double y, double width, double height)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.Layout.UpdateChildrenLayout()<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.Layout.OnSizeAllocated(double width, double height)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.VisualElement.SizeAllocated(double width, double height)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.VisualElement.SetSize(double width, double height)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.VisualElement.set_Bounds(Rectangle value)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.VisualElement.Layout(Rectangle bounds)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.Layout.LayoutChildIntoBoundingRegion(VisualElement child, Rectangle region)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.TemplatedView.LayoutChildren(double x, double y, double width, double height)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.Layout.UpdateChildrenLayout()<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.Layout.OnSizeAllocated(double width, double height)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.VisualElement.SizeAllocated(double width, double height)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.VisualElement.SetSize(double width, double height)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.VisualElement.set_Bounds(Rectangle value)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.VisualElement.Layout(Rectangle bounds)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.Layout.LayoutChildIntoBoundingRegion(View child, Rectangle region, SizeRequest childSizeRequest)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.StackLayout.LayoutChildren(double x, double y, double width, double height)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.Layout.UpdateChildrenLayout()<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.Layout.OnSizeAllocated(double width, double height)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.VisualElement.SizeAllocated(double width, double height)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.VisualElement.SetSize(double width, double height)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.VisualElement.set_Bounds(Rectangle value)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.VisualElement.Layout(Rectangle bounds)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.Layout.LayoutChildIntoBoundingRegion(VisualElement child, Rectangle region)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.TemplatedView.LayoutChildren(double x, double y, double width, double height)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.Layout.UpdateChildrenLayout()<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.Layout.OnIsVisibleChanged(bool oldValue, bool newValue)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
at Xamarin.Forms.VisualElement+<>c.<.cctor>b__212_2 (Xamarin.Forms.BindableObject bindable, System.Object oldvalue, System.Object newvalue) [0x00000] in <0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.BindableObject.SetValueActual(BindableProperty property, BindableObject.BindablePropertyContext context, object value, bool currentlyApplying, BindableObject.SetValueFlags attributes, bool silent)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.BindableObject.SetValueCore(BindableProperty property, object value, BindableObject.SetValueFlags attributes, BindableObject.SetValuePrivateFlags privateAttributes)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.BindableObject.SetValue(BindableProperty property, object value, bool fromStyle, bool checkAccess)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.BindableObject.SetValue(BindableProperty property, object value)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.VisualElement.set_IsVisible(bool value)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Ridr.Client.Controls.Tabs.OnTabSwitch(int index)<e011caed1f184b02a01254685e487e1d>:0
Ridr.Client.Controls.Tabs.OnSelectedIndexChanged(BindableObject bindable, object oldValue, object newValue)<e011caed1f184b02a01254685e487e1d>:0
Xamarin.Forms.BindableObject.SetValueActual(BindableProperty property, BindableObject.BindablePropertyContext context, object value, bool currentlyApplying, BindableObject.SetValueFlags attributes, bool silent)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.BindableObject.SetValueCore(BindableProperty property, object value, BindableObject.SetValueFlags attributes, BindableObject.SetValuePrivateFlags privateAttributes)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.BindingExpression.ApplyCore(object sourceObject, BindableObject target, BindableProperty property, bool fromTarget)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.BindingExpression.Apply(bool fromTarget)<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Xamarin.Forms.BindingExpression.BindingExpressionPart.<PropertyChanged>b__47_0()<0f1ce60dbc6b4e24af01294c7acf41c6>:0
Java.Lang.Thread.RunnableImplementor.Run()<6d5b488990324d4ca6d28e34a1cffa58>:0
Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this)<6d5b488990324d4ca6d28e34a1cffa58>:0
at (wrapper dynamic-method) System.Object:486506db-450f-4820-b242-5ff9da89432c (intptr,intptr)
mono.java.lang.RunnableImplementor.n_run(Native Method)
mono.java.lang.RunnableImplementor.run()RunnableImplementor.java:30
android.os.Handler.handleCallback()Handler.java:751
android.os.Handler.dispatchMessage()Handler.java:95
android.os.Looper.loop()Looper.java:241
android.app.ActivityThread.main()ActivityThread.java:6274
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run()ZygoteInit.java:886
com.android.internal.os.ZygoteInit.main()ZygoteInit.java:776
```

**Comment by tekinc** [comment]
Hey @jamesmontemagno,

Any update on this issue?

**Comment by samhouts** [comment]
@jamesmontemagno I think you're going to want to do some eager disposal, like we're doing here now. https://github.com/xamarin/Xamarin.Forms/pull/1063

**Comment by FrameV** [comment]
I'm experiencing the same object disposed exception on XF 2.4.0.

I'm not sure if some behaviour has changed in XF but it looks like the property changed handler in the view renderer isn't being unregistered. There's some commented out code [here](https://github.com/jamesmontemagno/Xamarin.Forms-PullToRefreshLayout/blob/90ac1e774ddeb80b1eff94719e08f091baedd705/PullToRefresh/PullToRefresh.Droid/PullToRefreshLayoutRenderer.cs#L353) that looks like it would fix my issue, at least it has for other custom renderers I have.

**Comment by jamesmontemagno** [comment]
@FrameV this does not fix your issue and i have no idea how to fix this as it only happens when you use it a weird way. Hence I have never fixed it as I have no idea.

**Comment by FrameV** [comment]
@jamesmontemagno thanks for the reply. I don't think I'm using it in such a weird way but it could be, I'll do some debugging tomorrow and see if I can help.

**Comment by FrameV** [comment]
I took a copy of the library and did some debugging in my solution.

I've found that the PropertyChanged event is never unregistered. I did not see my debugger hit the code at [this line](https://github.com/jamesmontemagno/Xamarin.Forms-PullToRefreshLayout/blob/90ac1e774ddeb80b1eff94719e08f091baedd705/PullToRefresh/PullToRefresh.Droid/PullToRefreshLayoutRenderer.cs#L74) at all. Is this a change in XF behaviour?

When I navigate to another page inside my app, dispose is called on the renderer.

When I return to the page and a binding in my app causes the PropertyChanged event to fire, I see the event fire on what is presumably the view on screen, and then the app crashes as I assume it is trying to call the event on the object that has since been disposed. 

Adding the commented out code back in fixes the issue for me on XF 2.4.0. It was also important to dispose of the VisualElementTracker too or else it would also cause an object disposed exception.

**Comment by paleicikas** [comment]
Xamarin Exception Stack:
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Refractored.XamForms.PullToRefresh.Droid.PullToRefreshLayoutRenderer'.
  at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00029] in <1d799d87381c4db5b1252825fd105b84>:0
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualBooleanMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00000] in <1d799d87381c4db5b1252825fd105b84>:0
  at Android.Views.View.get_IsInLayout () [0x0000a] in <c82a099136944d8aa96281cf061cbc12>:0
  at Xamarin.Forms.Platform.Android.VisualElementTracker.MaybeRequestLayout () [0x00016] in <398cf4d138ad48c7a756f39dfc252737>:0
  at Xamarin.Forms.Platform.Android.VisualElementTracker.HandleRedrawNeeded (System.Object sender, Xamarin.Forms.Internals.EventArg`1[T] e) [0x00049] in <398cf4d138ad48c7a756f39dfc252737>:0
  at (wrapper delegate-invoke) System.EventHandler`1[Xamarin.Forms.Internals.EventArg`1[Xamarin.Forms.VisualElement]]:invoke_void_object_TEventArgs (object,Xamarin.Forms.Internals.EventArg`1<Xamarin.Forms.VisualElement>)
  at Xamarin.Forms.VisualElement.BatchCommit () [0x00031] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.VisualElement.set_Bounds (Xamarin.Forms.Rectangle value) [0x00071] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.VisualElement.Layout (Xamarin.Forms.Rectangle bounds) [0x00000] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Layout.LayoutChildIntoBoundingRegion (Xamarin.Forms.VisualElement child, Xamarin.Forms.Rectangle region) [0x0016b] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Grid.LayoutChildren (System.Double x, System.Double y, System.Double width, System.Double height) [0x00152] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Layout.UpdateChildrenLayout () [0x000c7] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Layout.OnSizeAllocated (System.Double width, System.Double height) [0x0000f] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.VisualElement.SizeAllocated (System.Double width, System.Double height) [0x00000] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.VisualElement.SetSize (System.Double width, System.Double height) [0x00021] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.VisualElement.set_Bounds (Xamarin.Forms.Rectangle value) [0x0006c] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.VisualElement.Layout (Xamarin.Forms.Rectangle bounds) [0x00000] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Layout.LayoutChildIntoBoundingRegion (Xamarin.Forms.VisualElement child, Xamarin.Forms.Rectangle region) [0x0016b] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.AbsoluteLayout.LayoutChildren (System.Double x, System.Double y, System.Double width, System.Double height) [0x00046] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Layout.UpdateChildrenLayout () [0x000c7] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Layout.OnSizeAllocated (System.Double width, System.Double height) [0x0000f] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.VisualElement.SizeAllocated (System.Double width, System.Double height) [0x00000] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.VisualElement.SetSize (System.Double width, System.Double height) [0x00021] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.VisualElement.set_Bounds (Xamarin.Forms.Rectangle value) [0x0006c] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.VisualElement.Layout (Xamarin.Forms.Rectangle bounds) [0x00000] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Layout.LayoutChildIntoBoundingRegion (Xamarin.Forms.VisualElement child, Xamarin.Forms.Rectangle region) [0x0016b] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Page.LayoutChildren (System.Double x, System.Double y, System.Double width, System.Double height) [0x0010d] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Page.UpdateChildrenLayout () [0x000c6] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Page.OnSizeAllocated (System.Double width, System.Double height) [0x0000f] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Common.Pages.BaseContentPage.OnSizeAllocated (System.Double width, System.Double height) [0x00000] in <aa4148d4f7b047d6b0e2f30b307d3c67>:0
  at Xamarin.Forms.VisualElement.SizeAllocated (System.Double width, System.Double height) [0x00000] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.VisualElement.SetSize (System.Double width, System.Double height) [0x00021] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.VisualElement.set_Bounds (Xamarin.Forms.Rectangle value) [0x0006c] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.VisualElement.Layout (Xamarin.Forms.Rectangle bounds) [0x00000] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Layout.LayoutChildIntoBoundingRegion (Xamarin.Forms.VisualElement child, Xamarin.Forms.Rectangle region) [0x0000a] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Page.LayoutChildren (System.Double x, System.Double y, System.Double width, System.Double height) [0x0010d] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Page.UpdateChildrenLayout () [0x000c6] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Page.OnSizeAllocated (System.Double width, System.Double height) [0x0000f] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.VisualElement.SizeAllocated (System.Double width, System.Double height) [0x00000] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Page.ForceLayout () [0x0000d] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Page.set_ContainerArea (Xamarin.Forms.Rectangle value) [0x0001d] in <a7f3b60e25304b56ab3b4f0d8c85dcc3>:0
  at Xamarin.Forms.Platform.Android.AppCompat.TabbedPageRenderer.OnLayout (System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x000da] in <398cf4d138ad48c7a756f39dfc252737>:0
  at Xamarin.Forms.Platform.Android.FormsViewGroup.n_OnLayout_ZIIII (System.IntPtr jnienv, System.IntPtr native__this, System.Boolean p0, System.Int32 p1, System.Int32 p2, System.Int32 p3, System.Int32 p4) [0x00008] in <e0b7802c8dd141c9a08bc5c8ecb6bbd9>:0
  at (wrapper dynamic-method) System.Object:19b34139-b400-4a32-a374-7f3113a120cc (intptr,intptr,bool,int,int,int,int)

**Comment by elneilios** [comment]
@jamesmontemagno I have just experienced this crash also - for me it occurs when navigating pages quickly, before the content within the PullToRefreshLayout has finished rendering. I don't know if that information helps at all?

**Comment by raymondjstone** [comment]
I had this issue as well, but running VIsual Studio and administrator, cleaning then rebuilding the project cured it for me, this was however only an issue on the release version for Android, the debug version always worked ok

**Comment by elneilios** [comment]
Unfortunately we've had to remove PullToRefreshLayout from our project because we are experiencing this crash very often on Droid (iOS seems to be fine). I can reproduce this in two ways:

1. Our App asynchronously loads content into the the PullToRefreshLayout control on the first screen in our App (a MasterDetalPage). If I use the navigation menu to navigate to another page before the content rendering has completed, I get the ObjectDisposedException [StackTrace](https://gist.github.com/elneilios/b2de04b2dbb96a9aaeb88d6c2e1e7384)
2. Within the PullToRefreshLayout we have a CarouselView, I have an event handlers on that CarouselView that fire when the carousel scrolling begins and when it ends which I use to enable and disable IsPullToRefreshEnabled. In some circumstances we programatically scroll the carousel, if page navigation occurs before the carousel has stopped scrolling we get the ObjectDisposedException [StackTrace](https://gist.github.com/elneilios/c6c141fbd4fc09c7de3a06b3bd9e13bf).

In both cases you can see from the stacktrace that the exception is occuring within PullToRefreshLayoutRenderer.HandlePropertyChanged. So it must be case of needing to unregister from PropertyChanged events on disposal. Was there a reason for commenting out your code that did this? Would it hurt to reinstate it?

**Comment by mmierzwa** [comment]
I'm also experiencing the same problem. Any workaround for this?

**Comment by mmierzwa** [comment]
I think I finally managed to workaround this. I included the renderer code in my code base. 

Then I overridden all the properties and methods that throw `ObjectDisposedException` from the native part: `IsInLayout`, `IsLayoutRequested`, `Visibility` and few others. The overrides simply wrap the base call (or renderer code) in `try-catch` block with some logging. 
 I also added the constructor `PullToRefreshLayoutRenderer(IntPtr javaReference, JniHandleOwnership transfer)` (I observed `MissingMethodException` error related with that).

Since the error seems to appear on control disappearance it works in my case. Although it's ugly...

**Comment by paleicikas** [comment]
`PullToRefreshLayoutRenderer(IntPtr javaReference, JniHandleOwnership transfer)` should not be implemented at all, it hides usage of already disposed PullToRefreshLayoutRenderer object

**Comment by paleicikas** [comment]
As I understand, `MissingMethodException` means that PullToRefreshLayoutRenderer already disposed, and there is not need call any methods/properties. Its common problem with all android renderers.

**Comment by mmierzwa** [comment]
Got it. One error entrails the other. 
Still I found no other solution for this issue. I hope I will get rid of this workaround as soon as possible.

**Comment by raymondjstone** [comment]
Just to add to the mix, I get the disposed object issue as well now, but currently only when the screen is being rotated.

**Comment by bastianbecker21** [comment]
this old bug is not fixed yet?? I am facing this crash with Xamarin Forms 3.x. please help to fix, thx

**Comment by jochembroekhoff** [comment]
This seems to be highly related to the following Xamarin.Forms bug: https://github.com/xamarin/Xamarin.Forms/issues/2004

**Comment by vdmitrovich** [comment]
>>>this seems to be highly related to the following Xamarin.Forms bug: xamarin/Xamarin.Forms#2004

Just want to mention that this forms issue with accessing to disposed object is fixed in  3.2.0.729530-pre2 , but reported PullToRefresh crash is still happening.

>>> I narrowed it down to data binding the IsPullToRefreshEnabled property. If I remove data binding to that property it works without issue.

For me it does not help(actually I never had this binding) - still crashing on rotation.

**Comment by vdmitrovich** [comment]
Actually for me it helped to add dispose for Tracker property in PullToRefreshRender Dispose. So tracker will unregister from even handlers and will not try to access to disposed PullToRefreshRenderer.
Here:
` public class FaultTolerantPullToRefreshRenderer : PullToRefreshLayoutRenderer
    {

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            Tracker.Dispose();
        }
    }`

**Comment by otorcatf** [comment]
Thanks @vdmitrovich  for the fix, your solution works for me. In my case I have 3 pages with PullToRefreshLayout inside of a TabbedPage and the exception throws when I move between the pages.

**Comment by keannan5390** [comment]
I was having a similar issues so I pulled the full renderer code into my project. I noticed there is a lot of code commented out in the Dispose method in the android renderer. 

https://github.com/jamesmontemagno/Xamarin.Forms-PullToRefreshLayout/blob/4217e7dbe354163c6e9ab9d3ba54913e1d38e477/PullToRefresh/PullToRefresh.Droid/PullToRefreshLayoutRenderer.cs#L359

If i uncomment that code, the exception seems to go away.

**Comment by nielscup** [comment]
Same issue with XF 3.6.0.293080 and PullToRefresh 2.4.1 and 2.4.1.1-beta

**Comment by BogdanoVolcano** [comment]
I faced the same issue. But @vdmitrovich advice helped. Thank you!

**Comment by jamesmontemagno** [comment]
Can someone send a pr down :)

**Comment by dbwelch** [comment]
Looks like jon-mccall has a fix, can this be integrated into a PullToRefresh Nuget?  I use this all over my app, and, it was approved in Apple App Store, but, now I found this that causes the app to crash everywhere on Android, can someone add this fix and build?  Pretty please?

**Comment by SharpMobileCode** [comment]
> Looks like jon-mccall has a fix, can this be integrated into a PullToRefresh Nuget? I use this all over my app, and, it was approved in Apple App Store, but, now I found this that causes the app to crash everywhere on Android, can someone add this fix and build? Pretty please?

I agree and this is what should happen.  But we couldn't wait and ended up copying the platform renderer files and the content view into our own project and fixing it ourselves.  Fortunately it was pretty simple and straight forward with just a minor namespace change in our XAML files.  But I agree, the PR has been opened for almost a month and it's disappointing.

**Comment by dbwelch** [comment]
Thanks, I’m doing same.  But, I’m a newbie when it comes to adding manually, what is the namespace change you have to make?  I imported the project into my main solution, left the namespace as before (Refactored.XamForms.PullToRefresh) under Default Namespace under the Project Options.  I get a ClassNotFound exception on the PullToRefreshRenderer.

I’ve added the project under all projects and the Android target.  Is the directory relevant?

Sent from my iPhone

On May 16, 2019, at 6:00 PM, Ruben Macias <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks like jon-mccall has a fix, can this be integrated into a PullToRefresh Nuget? I use this all over my app, and, it was approved in Apple App Store, but, now I found this that causes the app to crash everywhere on Android, can someone add this fix and build? Pretty please?

I agree and this is what should happen. But we couldn't wait and ended up copying the platform renderer files and the content view into our own project and fixing it ourselves. Fortunately it was pretty simple and straight forward with just a minor namespace change in our XAML files. But I agree, the PR has been opened for almost a month and it's disappointing.

**Comment by SharpMobileCode** [comment]
> Thanks, I’m doing same. But, I’m a newbie when it comes to adding manually, what is the namespace change you have to make? I imported the project into my main solution, left the namespace as before (Refactored.XamForms.PullToRefresh) under Default Namespace under the Project Options. I get a ClassNotFound exception on the PullToRefreshRenderer. I’ve added the project under all projects and the Android target. Is the directory relevant?

Sorry for the confusion.  I kept the namespaces the same on the actual renderers and content view files.  Then on my XAML files that use `PullToRefreshLayout`, I adjusted the the PullToRefresh control namespace definition to my own assembly instead of the Refractored.XamForms.PullToRefresh assembly

**Old**
```csharp
<ContentPage 
    xmlns="http://xamarin.com/schemas/2014/forms" 
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
    x:Class="RefreshSample.Views.ScrollViewXamlPage"
    xmlns:controls="clr-namespace:Refractored.XamForms.PullToRefresh;assembly=Refractored.XamForms.PullToRefresh"
    Title="Xaml Scroll">
```

**New**
```csharp
<ContentPage 
    xmlns="http://xamarin.com/schemas/2014/forms" 
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
    x:Class="RefreshSample.Views.ScrollViewXamlPage"
    xmlns:controls="clr-namespace:Refractored.XamForms.PullToRefresh;assembly=MyAppAssemblyName"
    Title="Xaml Scroll">
```

Notice that the value of `xmlns:controls` is different. Instead of it being defined in the `Refractored.XamForms.PullToRefresh.dll`, it's defined in my own app assembly.

**Comment by dbwelch** [comment]
Ruben:
Thanks for the assistance and clarification.  But, where is "MyAssemblyName" defined?  My configuration seems very similar, but, just not sure where to pull the assembly parameter on the namespace for "controls".

Thanks!
David

________________________________

**Comment by dbwelch** [comment]
I've attempted to build this myself in my project, but, apparently I'm not able to get this configured correctly in my project.  The fix seems to be to comment out two lines of code, and do a build.  Am I looking at this correctly?  Can someone help do a Nuget build that can be pulled into the project?

**Comment by dbwelch** [comment]
Managed to pull in the PullToRefresh code into my project and get the Android build to run finally (yea!), but, for some reason can't call PullToRefreshLayoutRenderer.Init() in MainActivity.cs, as it doesn't find the class when I add "using Refractored.XamForms.PullToRefresh.Droid", really weird.  None of the PullToRefreshLayout's work, but, at least the app doesn't crash.  The error is "the type or namespace name 'XamForms' does not exist in the namespace 'Refractored'".  I'm using Refractored.MvvmHelpers from Nuget also, does it "take over" everything under 'Refractored', which is preventing the import?  Sorry for posting obviously newbie questions here, but, thought someone might be able to help, guess I have to change the namespace in the code also...?

**Comment by jochembroekhoff** [comment]
I can confirm that this PR appears to fix the issues we're experiencing.
But it reaises the question as towards why that piece of code originally had been commented out.

**Comment by Mustafa-ah** [comment]
can any one explain this!!!
 when i use this structure in my page i get that exception 
"System.ObjectDisposedException: Cannot access a disposed object. Object name: 
'Tasky.Droid.Renderers.PullToRefreshLayoutRenderer'."

`  <AbsoluteLayout Padding="0"
              Margin="0"
              VerticalOptions="FillAndExpand"
              HorizontalOptions="FillAndExpand"
              BackgroundColor="#FAFAFA">

        <ScrollView AbsoluteLayout.LayoutFlags="All" Margin="{OnPlatform Android='0,0,0,0', iOS='0,0,0,74'}"
                     AbsoluteLayout.LayoutBounds="0, 0, 1, 1">
            <customcontrol1:PullToRefreshLayout IsPullToRefreshEnabled="True"
                                               VerticalOptions="FillAndExpand"
              HorizontalOptions="FillAndExpand"
                             RefreshCommand="{Binding ViewModel.RefreshCommand}"
                            IsRefreshing="{Binding ViewModel.IsRefreshing}">
                <Grid  VerticalOptions="FillAndExpand"
              HorizontalOptions="FillAndExpand"
              RowSpacing="0" Padding="5"> ...`

but when i changed it like this it works fine ?!!

`<AbsoluteLayout Padding="0"
              Margin="0"
              VerticalOptions="FillAndExpand"
              HorizontalOptions="FillAndExpand"
              BackgroundColor="#FAFAFA">

       
            <customcontrol1:PullToRefreshLayout IsPullToRefreshEnabled="True"
                                               AbsoluteLayout.LayoutFlags="All"
                                                Margin="{OnPlatform Android='0,0,0,0', iOS='0,0,0,74'}"
                     AbsoluteLayout.LayoutBounds="0, 0, 1, 1"
                             RefreshCommand="{Binding ViewModel.RefreshCommand}"
                            IsRefreshing="{Binding ViewModel.IsRefreshing}">
            <ScrollView VerticalOptions="FillAndExpand"
              HorizontalOptions="FillAndExpand">
                <Grid  VerticalOptions="FillAndExpand"
              HorizontalOptions="FillAndExpand"
              RowSpacing="0" Padding="5">
...
    `

**Comment by K232** [comment]
@jamesmontemagno , any idea when this PR https://github.com/jamesmontemagno/Xamarin.Forms-PullToRefreshLayout/pull/66 will be released?

**Comment by RodSanford** [comment]
I can verify that this bug is still around. Android issue only at this point.  I am using Forms 4.2.0.848062 and have tried this with release version 2.4.1 and beta version 2.4.1.1-beta.  I can reproduce it.

**Comment by RodSanford** [comment]
> I can verify that this bug is still around. Android issue only at this point. I am using Forms 4.2.0.848062 and have tried this with release version 2.4.1 and beta version 2.4.1.1-beta. I can reproduce it.

JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self)
JniPeerMembers+JniInstanceMethods.InvokeVirtualBooleanMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
View.get_IsInLayout ()
ViewExtensions.MaybeRequestLayout (Android.Views.View view) D:\a\1\s\Xamarin.Forms.Platform.Android\ViewExtensions.cs:110
VisualElementTracker.HandleRedrawNeeded (System.Object sender, Xamarin.Forms.Internals.EventArg`1[T] e) D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementTracker.cs:185
(wrapper delegate-invoke) System.EventHandler`1[Xamarin.Forms.Internals.EventArg`1[Xamarin.Forms.VisualElement]].invoke_void_object_TEventArgs(object,Xamarin.Forms.Internals.EventArg`1<Xamarin.Forms.VisualElement>)
VisualElement.BatchCommit () D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:572
VisualElement.set_Bounds (Xamarin.Forms.Rectangle value) D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:308
VisualElement.Layout (Xamarin.Forms.Rectangle bounds) D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:686
Layout.LayoutChildIntoBoundingRegion (Xamarin.Forms.View child, Xamarin.Forms.Rectangle region, Xamarin.Forms.SizeRequest childSizeRequest) D:\a\1\s\Xamarin.Forms.Core\Layout.cs:319
StackLayout.LayoutChildren (System.Double x, System.Double y, System.Double width, System.Double height) D:\a\1\s\Xamarin.Forms.Core\StackLayout.cs:65
Layout.UpdateChildrenLayout () D:\a\1\s\Xamarin.Forms.Core\Layout.cs:266
Layout.OnSizeAllocated (System.Double width, System.Double height) D:\a\1\s\Xamarin.Forms.Core\Layout.cs:224
VisualElement.SizeAllocated (System.Double width, System.Double height) D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:784
Layout+<>c.<OnChildMeasureInvalidated>b__45_0 () D:\a\1\s\Xamarin.Forms.Core\Layout.cs:381
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.45(intptr,intptr)
