### ISSUE TITLE
PullToRefresh does not work on Android

### ISSUE THREAD

**Issue by BerserkShaa** [jamesmontemagno/Xamarin.Forms-PullToRefreshLayout#56]
PullToRefresh doesn't work with version Xamarin Forms 3.4 pre2

**Comment by BerserkShaa** [comment]
I get the following error "System.TypeLoadException: VTable setup of type Refractored.XamForms.PullToRefresh.Droid.PullToRefreshLayoutRenderer failed"

**Comment by dhirensham** [comment]
Same happening here.
PullToRefresh from nuget, v2.2.2
Xamarin.Forms v3.4.0.1008975
VS 2017 15.9.1

The iOS side works fine. On Android, I get the above error when calling 
            PullToRefreshLayoutRenderer.Init();
from MainActivity.OnCreate

**Comment by jennablackwell** [comment]
Getting the same exception as well!

**Comment by mduchev** [comment]
Yep, same here. Got the exception after I have tried upgrading to Forms 3.4 (latest stable)

**Comment by cooliopas** [comment]
Same here :(

**Comment by hrq-araujo** [comment]
Same error here! Looking forward to an answer

**Comment by vipero07** [comment]
Downgraded to `Xamarin.Forms v3.3.0.967583` and that seems to work. I guess we will have to wait on an update to Pull To Refresh to support Xamarin.Forms v3.4 (or patch it)

**Comment by PlymouthRock** [comment]
System.TypeLoadException: VTable setup of type Refractored.XamForms.PullToRefresh.Droid.PullToRefreshLayoutRenderer failed still generated in debug log when downgrading to Xamarin.Forms v3.3.0.967583.

However, it doesn't crash the app like it does in v3.4.

**Comment by andyvasilevich** [comment]
Fixed ?

**Comment by quentinR0bert** [comment]
I have the same issue with the XF 3.4.
The FFImageLoading haved the same issue (https://github.com/luberda-molinet/FFImageLoading/issues/1154).

He fix by rebuild his plugin with the new XF Package.

So we have to wait for the same i think or download the sourc, update the XF Package and build.

**Comment by andyvasilevich** [comment]
@jamesmontemagno  Can you update the control? Thank very much.

**Comment by umairjaved932** [comment]
is this fixed? I am encountering the same error, downgrading to xamarin 3.3 didn't solve the problem for me too .

**Comment by umairjaved932** [comment]
SOLVED this error by using the **pulltorefresh** as a local library in the project and then adding the the references directly from the library in xamarin.droid and xamarin.ios projects in Xamarin 3.4 version.

Thanks @bakhti346 for the help.

**Comment by Fredhn** [comment]
@umairjaved932 could you explain me how to fix it? I'm still trying to figure it out.

**Comment by bakhti346** [comment]
@Fredhn  Download this repository.

**Comment by quentinR0bert** [comment]
You have two possibility :

Dowload the source, open the solution, update the XF packages on the projects , build, remove the nuget package, put the DLL at references on yours projects in your app.

Or 

Download the source, add the projects to your solution, update the XF packages on the projects , build, remove the nuget package, add reference of the project in your project.

But with this solution you use a local version of the plugin and not anymore the version of James.

@umairjaved932 can you make a Merge Request of your fix, maybe like this James will make faster the update

**Comment by bakhti346** [comment]
@Fredhn Download Source, Add Pull Library to your solution and build the library with XF 3.4 and add references of the local library in your project  rebuild your App. Like @quentinR0bert  mentioned.

**Comment by umairjaved932** [comment]
@Fredhn i used the second method which @quentinR0bert  has mentioned above.  You can follow the steps, hope that might help. 

Yes, i had to use this as a local version to make things workout for me as soon as possible. 
Hope James with update the plugin sooner.

**Comment by Fredhn** [comment]
@quentinR0bert @bakhti346 @umairjaved932 thank you all!

**Comment by 007vel** [comment]
@bakhti346 Worked, Thanks.

**Comment by Fredhn** [comment]
@jamesmontemagno is there any prevision about when the correction for this issue will be released?

**Comment by Fredhn** [comment]
For those who get this problem until hot fix is not released, this is fixed the nuget package for download. Update your PullToRefreshLayout dll creating  a local package source and provide its directory as source.

[Refractored.XamForms.PullToRefresh.2.2.2.1.zip](https://github.com/jamesmontemagno/Xamarin.Forms-PullToRefreshLayout/files/2633024/Refractored.XamForms.PullToRefresh.2.2.2.1.zip)

**Comment by quentinR0bert** [comment]
Thanks for the others @Fredhn .
Can you put your version (used for the Nuget Package) of the source as a PullRequest for @jamesmontemagno  ?

**Comment by Fredhn** [comment]
> Thanks for the others @Fredhn .
> Can you put your version (used for the Nuget Package) of the source as a PullRequest for @jamesmontemagno ?

Sure, I'll try to do that.

**Comment by jamesmontemagno** [comment]
Please don't publish new packages send a pull request.

I am building this now.

**Comment by jamesmontemagno** [comment]
Fixed
